version: 1.0.{build}
image: Linux
build_cloud: anirudh-OptiPlex-7050
branches:
  # whitelist
  only:
    - master
skip_branch_with_pr: true
install:
- sh: >-
    set -e

    curl https://sh.rustup.rs -sSf > /tmp/sh.rustup.rs

    sh /tmp/sh.rustup.rs -y

    source $HOME/.cargo/env

    export PATH=$PATH:$HOME/.cargo/bin/

    rustup default nightly

build_script:
- sh: >-
    set -e

    export GUROBI_HOME="/opt/gurobi811/linux64"

    cargo build

    cargo run --bin denarii 10 10

    cargo run --bin gurobi_ffi

    cargo test

    echo "********ALL DONE*******"
